### PR TITLE
UI update for auction functions

### PR DESCRIPTION
**Pull request by nottotis**
[Regarding issue](https://github.com/FraktalNFT/dapp-frontend/issues/111)

(optional)run this command if any error on ssl
```
export NODE_OPTIONS=--openssl-legacy-provider
```

Part 1
http://localhost:3000/
image
Check if clicking does filter fixed price and auction.

Part 2
http://localhost:3000/list-nft
image
image

Check the changes of input when user click on either Fixed Price or Auction tabs.

Part 3
http://localhost:3000/
image
Note on "Auction Test Item", the bottom left side is changed from price to Countdown. 
Only two largest time unit is displayed at each time. To reduce information if too much countdown info is displayed.
- days and hours
- hours and mins
- mins and seconds

Part 4
Click on "Auction Test Item" or http://localhost:3000/nft/0xb02c6cf605e871d7ad975147372ab1227425cb61/auction
For this one, the already created auction page is tweaked and diplayed using sample item.
image

Part 5
After wallet is connected, go to http://localhost:3000/my-nfts
image

A new section named Auction is created for user that contributed in auctions.
Two sample items is already diplayed for an auction that is in progress(button grayed out), and ending auction(from greyed button to "Claim Fraktions").
Sellers Eth will be included on the Marketplace Profits section.

### CODE REVIEW

**Comment by nottotis** [comment]
Might need to allow CORS to able viewing Part 4
https://benborgers.com/posts/vercel-cors

**Comment by nottotis** [comment]
Updated UI with auction contract, still work in progress but yu could list and auction and contribute to auction now. 
Claiming will be added next to the UI.

A new contracts will be deployed to fix problems with new subgraph.

**Comment by nottotis** [comment]
Checks:
1. Open list-nft page then list nft
- make sure to select the Auction tab when listing
- set reserve price for 0.01 ETH, so we could participate in auction later and contribute more than 0.01 ETH
- Finish listing procedure until "4. List Auction"
2. Check if the auction is listed on the marketplace front page, might need to refresh if the subgraph API is still pending
3. Click on the auction card, then go to the bottom of the auction page to contribute more than the reserve price to the auction. (either with the same ETH account or another account)
- check if "Current Auction Reserve" changed after the contribution is complete.
4. Go to my-nft page, then check at Auctions section if there is your participated and listed auction (whichever applicable)
5. End auction at "My Auction" subsection auction card. After this, you could redeem the ETH(as seller) or Fraktions(as the participant) 
6. Check if ETH or Fraktions are distributed properly at [Rinkeby Contract](https://rinkeby.etherscan.io/address/0x2eaa5e7a501efa561b775aee95eef6a113bdd0e4)

Notes:
- Each Minted NFT == 10,000 Fraktions == 10,000 * 10^18 Fei in the new contract

**Comment by cryptnotiq** [comment]
@nottotis check issues: #131 #132  #133 #135 #136 

#134 is not critical, but believe it is subgraph-based.

**Pull request merged**
