### PR TITLE
v1 list style change

### PR DESCRIPTION
**Pull request by paul-harrison-jordan**
adjusted styling to match color and theme of other selectors on page!

### CODE REVIEW

**Comment by cryptnotiq** [comment]
@paul-harrison-jordan can you please also update the design on the import listing page? https://fraktal-dapp-git-fork-paul-harrison-jordan-list-type-fraktal.vercel.app/import-nft

**Comment by paul-harrison-jordan** [comment]
Sure thing, can you clarify what you want me to change on the page? I've attached a screenshot that shows the page currently, Do you want me to change the mint NFT and import NFT buttons to match what I did in my first commit? Or something else?

Screen Shot 2022-02-23 at 6 50 12 PM

**Comment by cryptnotiq** [comment]
@paul-harrison-jordan you need an NFT in your wallet to view the process. When you have one, you can click on it and it will take you to a similar page as the Mint Page, this is what needs to be udpated. You should find it in the import-nft page in the code.

**Comment by paul-harrison-jordan** [comment]
@cryptnotiq sounds good, I have an nft in my metamask on the eth mainnet, when I go to the page with my wallet connected it says I don't have any nfts, do you know what network the nft needs to be on in order to render on the page?
?

**Comment by cryptnotiq** [comment]
> @cryptnotiq sounds good, I have an nft in my metamask on the eth mainnet, when I go to the page with my wallet connected it says I don't have any nfts, do you know what network the nft needs to be on in order to render on the page? ?

rinkeby

**Pull request merged**
