### PR TITLE
Add Unit Information in Purchase Block (fixes #74)

### LINKED ISSUE #74: Add Unit Information in Purchase Block
Screen Shot 2021-12-07 at 12 54 19

In the box where user inputs # of fraktions to buy, put units. i.e Fraktions in light gray text so it is more clear.

Do the same with buyout offer by putting ETH in light gray text within the box.

### PR DESCRIPTION
**Pull request by vthonte**
Added ETH and FRANKTIONS placeholders in Purchase and Buy Block.

### CODE REVIEW

**Comment by cryptnotiq** [comment]
hey @vthonte instead of text being replaced by input value, it's supposed to remain static. [input value] Fraktions [button] /[input value] ETH [button]

**Comment by vthonte** [comment]
Format Input-Unit-Button used. @cryptnotiq Please review and let me know of any concerns.

**Comment by cryptnotiq** [comment]
@vthonte 

keep it same design style as the ETH style in this. No shite space. Fraktions with capital F
Screen Shot 2021-12-12 at 23 38 54

**Comment by vthonte** [comment]
@cryptnotiq Updated. Please check and let me know.

**Comment by cryptnotiq** [comment]
perfect @vthonte

**Pull request merged**
