### PR TITLE
feat: add ens username and avatar support

### PR DESCRIPTION
**Pull request by bigint**
Screenshot 2022-02-09 at 8 28 11 AM

cc @cryptnotiq

### CODE REVIEW

**Comment by bigint** [comment]
If this PR get's merged we will add the app to our https://ens.domains homepage and tweet from https://twitter.com/ensecosystem 🤗

**Comment by cryptnotiq** [comment]
hey @bigint - this is great! doesn't seem to be working on rinkeby though, so we'll test and merge this once the dapp is deployed on main-net

**Comment by bigint** [comment]
@cryptnotiq it is suggested to use ens only on mainnet, we can use the same name across all chains 🤗

**Comment by cryptnotiq** [comment]
@bigint we've deployed on main-net, could you update your branch so we can test and merge?

**Pull request closed without merging**
