### PR TITLE
Fix Scroll Bug

### PR DESCRIPTION
**Pull request by naftalimurgor**
This pull request close this issue: https://github.com/FraktalNFT/dapp-frontend/issues/172

According to the Nextjs docs call to `router.push` takes 2 other option arguments, `router.push(url, as, options)`

The third argument is an object with a `scroll` propery amongst other properties.
`scroll` determines whether to to enable `scroll` animations on navigation to the `url` provided, and is by default set to `true`

We can disable this behavior, responsible for the scroll glitch by adjusting our `router.push()` from `router.push('/my-nfts')` to `router.push('my-nfts, null, {scroll: false)` 

This resolves the scroll glitch for the navigations  to new pages

Update: Fix typos
Sources: https://nextjs.org/docs/api-reference/next/router#routerpush

### CODE REVIEW

**Comment by cryptnotiq** [comment]
hey @naftalimurgor can you pull latest updates to your branch so I can merge?

**Comment by naftalimurgor** [comment]
hello @cryptnotiq 
Sure thing, let me resolve the merge conflict shortly

**Comment by naftalimurgor** [comment]
Hello @cryptnotiq 
I resolved the merge conflict. Let me of any other issues.

**Comment by cryptnotiq** [comment]
@naftalimurgor hey can you submit the work on gitcoin so I can send payment? Also tagged you in another task we have open

**Pull request merged**
